<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
          <groupId>com.zwei</groupId>
          <artifactId>zwei</artifactId>
          <version>3.9.0</version>
    </parent>

    <artifactId>module-system</artifactId>
    <packaging>pom</packaging>
    <description>
        通用业务模块 - 支撑上层的通用业务服务
        模块包含：用户管理、角色管理、菜单管理、部门管理、字典管理
    </description>

    <modules>
        <module>zwei-system</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

</project>