<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
          <groupId>com.zwei</groupId>
          <artifactId>module-iot</artifactId>
          <version>3.9.0</version>
    </parent>

    <groupId>com.zwei</groupId>
    <artifactId>module-iot-device</artifactId>




    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.zwei</groupId>
            <artifactId>zwei-common</artifactId>
        </dependency>
        
        <!-- 添加IoT存储MySQL实现模块依赖 -->
        <dependency>
            <groupId>com.zwei</groupId>
            <artifactId>iot-storage-mysql</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <!-- 添加iot-core模块依赖，因为需要使用ThingModel类 -->
        <!--        <dependency>-->
        <!--            <groupId>com.zwei</groupId>-->
        <!--            <artifactId>module-iot-core</artifactId>-->
        <!--            <version>${project.version}</version>-->
        <!--        </dependency>-->
        
        <!-- 添加jackson-databind依赖，用于JSON处理 -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>

</project>