/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    CascadeSelector: typeof import('./src/components/CascadeSelector.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ContainerCard: typeof import('./src/components/ContainerCard.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    Echarts: typeof import('./src/components/echarts.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    MonitorChart: typeof import('./src/components/MonitorChart.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    StatBubble: typeof import('./src/components/StatBubble.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}
