package com.zwei.iot.timeseries.compute;

import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 将多个计算属性脚本片段拼装成一个 Groovy 源文件。
 *
 * <p>输出结构:
 * <pre>
 * def calc_attr1(curData, prevData) { /* user code 1 *\/ }
 * def calc_attr2(curData, prevData) { /* user code 2 *\/ }
 * def compute(curData, prevData) {
 *     def out = new LinkedHashMap&lt;String, Object&gt;()
 *     try { out.put('attr1', calc_attr1(curData, prevData)); curData.get('properties').putAll(out) }
 *          catch (Exception e) { /* skip *\/ }
 *     try { out.put('attr2', calc_attr2(curData, prevData)); curData.get('properties').putAll(out) }
 *          catch (Exception e) { /* skip *\/ }
 *     return out
 * }
 * </pre>
 *
 * <p>缓存 key = SHA-256(每条属性 id:code:script 拼接), 内容变化自动失效。
 */
@Service
public class ComputedScriptAssembler {

    /** key = sha256(attrs 指纹), value = 拼装后的 Groovy 源 */
    private final ConcurrentHashMap<String, String> cache = new ConcurrentHashMap<>();

    /**
     * 拼装 Groovy 源; 命中缓存则直接返回。内部会按 sortOrder 升序排序后再拼装,
     * 保证求值顺序与字典配置一致(即使调用方传入乱序)。
     *
     * @param attrs 计算属性列表(可为空)
     * @return 拼装后的 Groovy 源, 空列表返回空字符串
     */
    public String assemble(List<ComputedAttribute> attrs) {
        if (attrs == null || attrs.isEmpty()) return "";

        List<ComputedAttribute> sorted = new ArrayList<>(attrs);
        sorted.sort(Comparator.comparing(
                a -> a.sortOrder() == null ? Integer.MAX_VALUE : a.sortOrder()));

        String cacheKey = buildCacheKey(sorted);
        return cache.computeIfAbsent(cacheKey, k -> doAssemble(sorted));
    }

    private String doAssemble(List<ComputedAttribute> attrs) {
        StringBuilder sb = new StringBuilder(1024);
        sb.append("// Auto-generated by ComputedScriptAssembler. Do not edit.\n\n");

        // 1. 函数定义
        for (ComputedAttribute a : attrs) {
            sb.append("def calc_").append(a.code())
              .append("(curData, prevData) {\n")
              .append("    // === ").append(a.name()).append(" ===\n")
              .append(a.calcScript())
              .append("\n}\n\n");
        }

        // 2. 主入口 compute
        sb.append("def compute(curData, prevData) {\n");
        sb.append("    def out = new LinkedHashMap<String, Object>()\n");
        for (ComputedAttribute a : attrs) {
            sb.append("    try {\n");
            sb.append("        def __v = calc_").append(a.code()).append("(curData, prevData)\n");
            sb.append("        out.put('").append(a.code()).append("', __v)\n");
            sb.append("        if (curData != null && curData.get('properties') != null) curData.get('properties').putAll(out)\n");
            sb.append("    } catch (Exception e) { out.put('__err_").append(a.code()).append("', e.getClass().getSimpleName() + ': ' + e.getMessage()) }\n");
        }
        sb.append("    return out\n");
        sb.append("}\n");

        return sb.toString();
    }

    private String buildCacheKey(List<ComputedAttribute> attrs) {
        StringBuilder raw = new StringBuilder();
        for (ComputedAttribute a : attrs) {
            raw.append(a.id()).append(':')
               .append(a.code()).append(':')
               .append(a.calcScript() == null ? "" : a.calcScript()).append('|');
        }
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(raw.toString().getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder(digest.length * 2);
            for (byte b : digest) hex.append(String.format("%02x", b));
            return hex.toString();
        } catch (Exception e) {
            // 不应失败; 退化到原值 hashCode
            return Integer.toString(raw.hashCode());
        }
    }
}
