<template>
  <el-dialog
      v-model="visible"
      title="指标判据编辑"
      width="720px"
      destroy-on-close
      :close-on-click-modal="false"
      @opened="onOpened"
  >
    <!-- ===== 2.1 表达式 textarea ===== -->
    <div class="expr-section">
      <div class="section-label">判据表达式</div>
      <textarea
          ref="textareaRef"
          v-model="localExpr"
          class="expr-textarea"
          rows="5"
          placeholder="输入表达式，如：水位(m) > 10 且 小时变化 > 5"
          spellcheck="false"
      ></textarea>
      <div v-if="validationError" class="expr-error">{{ validationError }}</div>
    </div>

    <!-- ===== 2.2 快捷插入面板 ===== -->
    <div class="quick-panel">
      <!-- 逻辑运算符 -->
      <div class="quick-group">
        <span class="quick-label">逻辑运算符</span>
        <div class="quick-btns">
          <el-button size="small" v-for="op in logicalOps" :key="op" @click="insertAtCursor(' ' + op + ' ')">
            {{ op }}
          </el-button>
        </div>
      </div>
      <!-- 关系运算符 -->
      <div class="quick-group">
        <span class="quick-label">关系运算符</span>
        <div class="quick-btns">
          <el-button size="small" v-for="op in relationOps" :key="op" @click="insertAtCursor(' ' + op + ' ')">
            {{ op }}
          </el-button>
        </div>
      </div>
      <!-- 指标（动态加载） -->
      <div class="quick-group" v-if="indicators.length > 0">
        <span class="quick-label">指标</span>
        <div class="quick-btns">
          <el-button
              size="small"
              v-for="ind in indicators"
              :key="ind.code"
              @click="insertAtCursor(ind.name + ' ')"
          >
            {{ ind.name }}<span v-if="ind.unit" class="ind-unit">({{ ind.unit }})</span>
          </el-button>
        </div>
      </div>
    </div>

    <!-- ===== 2.3 说明 ===== -->
    <div class="desc-section">
      <div class="desc-header">
        <span class="section-label">说明</span>
        <el-button size="small" text type="primary" @click="autoGenerateDesc" :disabled="!localExpr.trim()">
          一键生成说明
        </el-button>
      </div>
      <el-input
          v-model="localDesc"
          type="textarea"
          :rows="2"
          placeholder="告警条件的业务描述（非必填）"
      />
    </div>

    <template #footer>
      <el-button @click="handleCancel">取消</el-button>
      <el-button type="primary" @click="handleConfirm">确定</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import {nextTick, ref, watch} from 'vue'
import {ElMessage} from 'element-plus'

// ── Props ──
const props = defineProps<{
  modelValue: boolean
  expression: string
  description: string
  indicators: { code: string; name: string; unit?: string }[]
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  confirm: [payload: { expression: string; description: string }]
}>()

// ── 双向绑定 visible ──
const visible = ref(props.modelValue)
watch(() => props.modelValue, v => {
  visible.value = v
})
watch(visible, v => emit('update:modelValue', v))

// ── 本地状态 ──
const localExpr = ref(props.expression)
const localDesc = ref(props.description)
const validationError = ref<string | null>(null)
const textareaRef = ref<HTMLTextAreaElement | null>(null)

// 对话框打开时重置
function onOpened() {
  localExpr.value = props.expression
  localDesc.value = props.description
  validationError.value = null
}

// ── 常量 ──
const logicalOps = ['且', '或']
const relationOps = ['>', '<', '>=', '<=', '==', '!=', '(', ')']

// ── 光标位置插入 ──
function insertAtCursor(text: string) {
  const el = textareaRef.value
  if (!el) {
    localExpr.value += text
    return
  }
  const start = el.selectionStart
  const end = el.selectionEnd
  localExpr.value = localExpr.value.slice(0, start) + text + localExpr.value.slice(end)
  nextTick(() => {
    el.focus()
    const pos = start + text.length
    el.setSelectionRange(pos, pos)
  })
}

// ── 语法校验 ──
function validateExpression(expr: string): string | null {
  if (!expr.trim()) return '表达式不能为空'
  if (/[><=!]\s*[><=!]/.test(expr) && !/[><=!]=/.test(expr)) return '表达式存在连续运算符'
  const open = (expr.match(/\(/g) || []).length
  const close = (expr.match(/\)/g) || []).length
  if (open !== close) return '括号不匹配'
  return null
}

// ── 一键生成说明 ──
function autoGenerateDesc() {
  let desc = localExpr.value
      .replace(/\s*>=\s*/g, '大于等于')
      .replace(/\s*<=\s*/g, '小于等于')
      .replace(/\s*!=\s*/g, '不等于')
      .replace(/\s*==\s*/g, '等于')
      .replace(/\s*>\s*/g, '大于')
      .replace(/\s*<\s*/g, '小于')
      .replace(/\s+且\s+/g, ' 并且 ')
      .replace(/\s+或\s+/g, ' 或者 ')
      .replace(/[\(\)]/g, '')
  localDesc.value = desc
}

// ── 确定 / 取消 ──
function handleCancel() {
  visible.value = false
}

function handleConfirm() {
  validationError.value = validateExpression(localExpr.value)
  if (validationError.value) {
    ElMessage.warning(validationError.value)
    return
  }
  emit('confirm', {expression: localExpr.value, description: localDesc.value})
  visible.value = false
}
</script>

<style scoped>
/* ── 表达式 textarea ── */
.expr-section {
  margin-bottom: 16px;
}

.section-label {
  display: block;
  font-size: 14px;
  font-weight: 500;
  color: #303133;
  margin-bottom: 8px;
}
.expr-textarea {
  width: 100%;
  box-sizing: border-box;
  padding: 10px 12px;
  font-size: 14px;
  font-family: 'Consolas', 'Courier New', monospace;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  resize: vertical;
  outline: none;
  transition: border-color .2s;
}

.expr-textarea:focus {
  border-color: #409eff;
}

.expr-error {
  margin-top: 6px;
  font-size: 12px;
  color: #f56c6c;
}

/* ── 快捷插入面板 ── */
.quick-panel {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 12px;
  background: #fafafa;
  border-radius: 6px;
  margin-bottom: 16px;
}

.quick-group {
  display: flex;
  align-items: flex-start;
  gap: 10px;
}
.quick-label {
  min-width: 80px;
  font-size: 13px;
  color: #909399;
  padding-top: 4px;
  text-align: right;
}

.quick-btns {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  flex: 1;
}

.ind-unit {
  font-size: 11px;
  color: inherit;
  opacity: .7;
}

/* ── 说明区 ── */
.desc-section {
}

.desc-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}
</style>
